### ISSUE TITLE
Better indicate calculated fields in documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-summarize#138]
It's helpful to quickly see which fields are calculated, to know what you don't need to calculate yourself.

**Comment by Bjwebb** [comment]
I think this will be a manual task, rather than something we detect automatically.

Would we want this as an extra column on https://kingfisher-summarize.readthedocs.io/en/latest/database.html? Those tables are generated from https://github.com/open-contracting/kingfisher-summarize/blob/main/sql/final/docs.sql, but I'm not sure we can add an extra attribute to that, only add to the descriptive text. I could do that and split it out into an extra column in the docs, although maybe that's a bit brittle.

@jpmckinney What do you think?

**Comment by jpmckinney** [comment]
Hmm, looking at the comments, there are a lot of small things to fix. I'll commit something shortly.

**Comment by jpmckinney** [comment]
I've made the commit now 58a17b7. I think I'll resolve the rest.

**Comment by jpmckinney** [comment]
Done. I found and fixed three bugs while doing this #199 #200 #201. See changelog: https://kingfisher-summarize.readthedocs.io/en/latest/changelog.html

There is now a `test_docs.py` which will issue warnings but never fail if column comments are not as expected. At this point, column descriptions are deterministic, so we might prefer to auto-generate `docs.sql` instead of checking its content.

However, the design of Summarize is for analysts to be able to edit the SQL files without editing any Python, so I'll leave it for now.
