### ISSUE TITLE
Inconsistent column naming

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-summarize#140]
We should add developer documentation to avoid these naming issues.

Inconsistent patterns are:

* `total_*` vs `*_count`: A numeric/integer/bigint field to count the number of items in an array. We should prefer `total_` to avoid confusion with `_counts` below. `total_` is followed by a plural word, whereas `_count` is inconsistently prefixed by plural and singular words.
* JSON field names are inconsistently prefixed by the parent object's name, e.g. `contract_status` but `datesigned`.
* Intermediate JSON objects are inconsistently included, e.g. `tender_value_amount` but `unit_amount`.
* JSON field names are inconsistently written, e.g. `additional_classification_count` (underscored and singularized) but `parties_additionalidentifiers_count` (same as JSON), or  `award_id` (underscored) but `planning_budget_projectid`.

Other strangeness:

* Why `supplier_parties_id` and not `supplier_id`? (same for other party roles)
* `award_amount` should indicate that it is an aggregate (e.g. `sum_awards_amount`). (same for `contract_amount`)

Consistent patterns are:

* `*_counts`: A JSON object in which the key is a value and the value is the number of occurrences of that value.
* `link_to_*`: Whether the reference can resolve.

**Comment by duncandewhurst** [comment]
In general, I'm in favour of fixing the inconsistent patterns, aligning field names with the schema and writing some developer documentation.

> JSON field names are inconsistently prefixed by the parent object's name, e.g. `contract_status` but `datesigned`.

I guess the prefixes were added to make it easier to write select statements when joining two tables which contain properties which would otherwise have the same name (e.g. `tender_status` and `contract_status`) and omitted when this isn't an issue (e.g. `date_signed`) for brevity, but it would be easier to write queries without needing to reference the documentation if the field names were consistently prefixed with the parent object's name.

> Why supplier_parties_id and not supplier_id? (same for other party roles)

This may have been to distinguish from the supplier organization identifier, but I would prefer the naming to be consistent with the schema.

**Comment by mrshll1001** [comment]
I'm similarly generally in favour of naming with the schema; wrt to the `tender_status` and `contract_status` issue postgres will force someone to use the table name in front of it, and if they want to rename the output using `AS` they can. Agree with @duncandewhurst that the fewer times I need to check up the documentation the better.

Agree that any aggregate field should indicate that it's a `sum` and I similarly prefer `total_*` vs `*_count`

**Comment by Bjwebb** [comment]
I've fixed all the inconsistencies I can see in this PR: https://github.com/open-contracting/kingfisher-summarize/pull/196

I've removed the parent object names from prefixing the column names, e.g. `award_title` -> `title`. But, I can't do this for id fields, as `id` is already the release or record id, so I've left them as they are e.g. `contract_id`. This also makes it easier to join with `USING`. Additionally, for easier joins, and because they don't correspond to JSON fields, I've kept indices (e.g. `contract_index`) and `release_type` as they are.

Currently (https://github.com/open-contracting/kingfisher-summarize/pull/196/commits/0322226fd4f3f8af54b02607a18a84047efde6ed), I have `award_id` in the award table, to be consitent with other ids, but `awardid` in the contracts table, because that's how the JSON field there is named. I think this is okay, because the fields are named differently in the JSON (one is `id` and one `awardID`).

**Comment by jpmckinney** [comment]
Those choices make sense 👍

**Comment by Bjwebb** [comment]
Do we want to rename the tables as well? I see we have `awards_summary` (plural), but `release_summary` (singular), and `award_documents_summary` where "award" is singular.

**Comment by jpmckinney** [comment]
Yes, I think the tables are fine. They are consistent, in the way Duncan described. `release_summary` is a bit weird, as it's referring to the "thing" as a whole, whereas `tender_summary`, `planning_summary`, etc. are referring to a section of the thing, but I don't know a better name.
