### ISSUE TITLE
add-view: validate --name argument and error if not lowercase

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#169]
PostgreSQL always folds unquoted names to lowercase ([docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)).

So if you use `add-view` to create a schema with a custom name which includes uppercase letters, then you need to quote the schema name in your queries, and the error message if you don't isn't particularly helpful.

To avoid this situation occuring it might just be easiest to always convert the `--name` argument to lowercase before creating the schema.

Alternatively, if there is a use case for schema names which contain uppercase letters, then we should add a note to the [docs](https://kingfisher-views.readthedocs.io/en/latest/cli/use.html#customize-the-schema-s-name).

cc @odscrachel

**Comment by jpmckinney** [comment]
Rather than lowercasing the argument, the argument should validate the input and error if not lowercase.

That way, the user won't be surprised that the schema is a lowercase version of their input. (We could alternately issue a warning to inform the user of the lowercasing, but Views is very noisy and I suspect not everyone reads everything.)
