### ISSUE TITLE
Add fields to contract_implementation_transactions_summary table

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-summarize#54]
Add:

* date
* payer fields (i.e. same fields as in award_suppliers_summary)
* payee fields (i.e. same fields as in award_suppliers_summary)
* transaction (jsonb blob of the transaction)

**Comment by jpmckinney** [comment]
For buyer and procuring entity, we have additional tables, even though they are 1:1 with their parent (the release). (It could have maybe made more sense to put them on the release_summary, since it is very common to want to filter by buyer, and joining buyer_summary to release_summary is expensive. That said, in practice, users like Camila just index into the JSONB, which doesn't really have any performance impact.)

In the case of payer and payee, they are rarely disclosed (as discussed in #6), and as such are rarely the subject of analysis. Adding more tables would just be overhead (moreso in terms of code maintenance than in terms of summary generation).

If we were to add fields directly on the transactions summary, it would be inconsistent with our approach for other parties, and in general we prefer a common approach. A party has 10 fields, which is a lot for users to ignore (since they will usually be empty), e.g.:

* payer
* payer_id
* name
* identifier
* unique_identifier_attempt
* additionalidentifiers_ids
* total_additionalidentifiers
* link_to_parties
* link_with_role
* party_index

So, for this issue, I will just add date and transaction.

**Comment by jpmckinney** [comment]
`transaction` was added in 3cac61f3, as an unrelated change.
